package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"path/filepath"
)

func main() {
	if len(os.Args) != 3 {
		log.Fatalf("Usage: go run generate.go <input_schema.json> <output_schemareader.go>")
	}

	inputFile := os.Args[1]
	outputFile := os.Args[2]

	schemaBytes, err := os.ReadFile(inputFile)
	if err != nil {
		log.Fatalf("Failed to read schema file: %v", err)
	}

	// Escape backticks in the JSON payload so we can embed it inside a raw string literal
	schemaString := bytes.ReplaceAll(schemaBytes, []byte("`"), []byte("`+\"`\"+`"))

	outDir := filepath.Dir(outputFile)
	if err := os.MkdirAll(outDir, 0755); err != nil {
		log.Fatalf("Failed to create output directory: %v", err)
	}

	goCode := fmt.Sprintf(`// Code generated by generators/go/generate-reader.go. DO NOT EDIT.
package validator

import (
	"encoding/json"
	"fmt"
	"net/netip"
	"net/url"
	"regexp"
	"strconv"
	"strings"
)

// SchemaJSON contains the fully resolved uCentral JSON schema
const SchemaJSON = `+"`%s`"+`

type Schema struct {
	Type                 interface{}             `+"`json:\"type\"`"+`
	Properties           map[string]*Schema      `+"`json:\"properties\"`"+`
	PatternProperties    map[string]*Schema      `+"`json:\"patternProperties\"`"+`
	Items                *Schema                 `+"`json:\"items\"`"+`
	Required             []string                `+"`json:\"required\"`"+`
	Enum                 []interface{}           `+"`json:\"enum\"`"+`
	Minimum              *float64                `+"`json:\"minimum\"`"+`
	Maximum              *float64                `+"`json:\"maximum\"`"+`
	MinLength            *int                    `+"`json:\"minLength\"`"+`
	MaxLength            *int                    `+"`json:\"maxLength\"`"+`
	MinItems             *int                    `+"`json:\"minItems\"`"+`
	MaxItems             *int                    `+"`json:\"maxItems\"`"+`
	Format               string                  `+"`json:\"format\"`"+`
	Pattern              string                  `+"`json:\"pattern\"`"+`
	OneOf                []*Schema               `+"`json:\"oneOf\"`"+`
	AnyOf                []*Schema               `+"`json:\"anyOf\"`"+`
	AllOf                []*Schema               `+"`json:\"allOf\"`"+`
	AdditionalProperties *bool                   `+"`json:\"additionalProperties\"`"+`
}

var rootSchema *Schema
var compiledPatterns map[string]*regexp.Regexp

func init() {
	if err := json.Unmarshal([]byte(SchemaJSON), &rootSchema); err != nil {
		panic(fmt.Sprintf("failed to load embedded schema: %%v", err))
	}
	compiledPatterns = make(map[string]*regexp.Regexp)
	precompilePatterns(rootSchema)
}

func precompilePatterns(s *Schema) {
	if s == nil { return }
	if s.Pattern != "" {
		compiledPatterns[s.Pattern] = regexp.MustCompile(s.Pattern)
	}
	for k, v := range s.PatternProperties {
		compiledPatterns[k] = regexp.MustCompile(k)
		precompilePatterns(v)
	}
	for _, v := range s.Properties {
		precompilePatterns(v)
	}
	precompilePatterns(s.Items)
}

func Validate(configJSON []byte) error {
	var v interface{}
	if err := json.Unmarshal(configJSON, &v); err != nil {
		return fmt.Errorf("invalid json payload: %%w", err)
	}
	if errs := validateNode(rootSchema, v, "$"); len(errs) > 0 {
		return fmt.Errorf("validation failed: %%s", strings.Join(errs, "; "))
	}
	return nil
}

func validateNode(s *Schema, v interface{}, path string) []string {
	if s == nil { return nil }
	var errs []string

	if v == nil {
		if s.Type == "null" { return nil }
		return []string{fmt.Sprintf("%%s: must not be null", path)}
	}

	// 1. Type validation
	if s.Type != nil {
		validType := false
		switch t := s.Type.(type) {
		case string:
			validType = checkType(t, v)
		case []interface{}:
			for _, allowedType := range t {
				if checkType(fmt.Sprint(allowedType), v) {
					validType = true
					break
				}
			}
		}
		if !validType {
			return []string{fmt.Sprintf("%%s: invalid type", path)}
		}
	}

	// 2. Object validation
	if obj, ok := v.(map[string]interface{}); ok {
		for _, req := range s.Required {
			if _, exists := obj[req]; !exists {
				errs = append(errs, fmt.Sprintf("%%s: missing required property '%%s'", path, req))
			}
		}
		for key, val := range obj {
			matched := false
			if propSchema, exists := s.Properties[key]; exists {
				errs = append(errs, validateNode(propSchema, val, path+"."+key)...)
				matched = true
			}
			for pat, propSchema := range s.PatternProperties {
				if r := compiledPatterns[pat]; r != nil && r.MatchString(key) {
					errs = append(errs, validateNode(propSchema, val, path+"."+key)...)
					matched = true
				}
			}
			if !matched && s.AdditionalProperties != nil && !*s.AdditionalProperties {
				errs = append(errs, fmt.Sprintf("%%s.%%s: additional property is not allowed", path, key))
			}
		}
	}

	// 3. Array validation
	if arr, ok := v.([]interface{}); ok {
		if s.MinItems != nil && len(arr) < *s.MinItems {
			errs = append(errs, fmt.Sprintf("%%s: must have at least %%d items", path, *s.MinItems))
		}
		if s.MaxItems != nil && len(arr) > *s.MaxItems {
			errs = append(errs, fmt.Sprintf("%%s: must have at most %%d items", path, *s.MaxItems))
		}
		if s.Items != nil {
			for i, item := range arr {
				errs = append(errs, validateNode(s.Items, item, fmt.Sprintf("%%s[%%d]", path, i))...)
			}
		}
	}

	// 4. String validation
	if str, ok := v.(string); ok {
		if s.MinLength != nil && len(str) < *s.MinLength {
			errs = append(errs, fmt.Sprintf("%%s: length must be >= %%d", path, *s.MinLength))
		}
		if s.MaxLength != nil && len(str) > *s.MaxLength {
			errs = append(errs, fmt.Sprintf("%%s: length must be <= %%d", path, *s.MaxLength))
		}
		if s.Pattern != "" {
			if r := compiledPatterns[s.Pattern]; r != nil && !r.MatchString(str) {
				errs = append(errs, fmt.Sprintf("%%s: does not match pattern %%s", path, s.Pattern))
			}
		}
		if s.Format != "" {
			if !checkFormat(s.Format, str) {
				errs = append(errs, fmt.Sprintf("%%s: invalid format '%%s'", path, s.Format))
			}
		}
	}

	// 5. Number validation
	if num, ok := v.(float64); ok {
		if s.Minimum != nil && num < *s.Minimum {
			errs = append(errs, fmt.Sprintf("%%s: must be >= %%v", path, *s.Minimum))
		}
		if s.Maximum != nil && num > *s.Maximum {
			errs = append(errs, fmt.Sprintf("%%s: must be <= %%v", path, *s.Maximum))
		}
	}

	// 6. Enum validation
	if len(s.Enum) > 0 {
		matched := false
		for _, e := range s.Enum {
			if fmt.Sprint(e) == fmt.Sprint(v) { // lazy comparison
				matched = true
				break
			}
		}
		if !matched {
			errs = append(errs, fmt.Sprintf("%%s: value not in enum", path))
		}
	}

	if len(s.OneOf) > 0 {
		matchCount := 0
		for i, subSchema := range s.OneOf {
			if len(validateNode(subSchema, v, fmt.Sprintf("%s.oneOf[%d]", path, i))) == 0 {
				matchCount++
			}
		}
		if matchCount != 1 {
			errs = append(errs, fmt.Sprintf("%%s: must match exactly one schema in oneOf", path))
		}
	}

	if len(s.AnyOf) > 0 {
		matched := false
		for i, subSchema := range s.AnyOf {
			if len(validateNode(subSchema, v, fmt.Sprintf("%s.anyOf[%d]", path, i))) == 0 {
				matched = true
				break
			}
		}
		if !matched {
			errs = append(errs, fmt.Sprintf("%%s: must match at least one schema in anyOf", path))
		}
	}

	if len(s.AllOf) > 0 {
		for _, subSchema := range s.AllOf {
			subErrs := validateNode(subSchema, v, path)
			if len(subErrs) > 0 {
				errs = append(errs, subErrs...)
			}
		}
	}

	return errs
}

func checkType(expected string, v interface{}) bool {
	switch expected {
	case "string":
		_, ok := v.(string)
		return ok
	case "number":
		_, ok := v.(float64)
		return ok
	case "integer":
		f, ok := v.(float64)
		return ok && f == float64(int64(f))
	case "boolean":
		_, ok := v.(bool)
		return ok
	case "object":
		_, ok := v.(map[string]interface{})
		return ok
	case "array":
		_, ok := v.([]interface{})
		return ok
	default:
		return true // ignore unknown
	}
}

func checkFormat(format string, val string) bool {
	switch format {
	case "ipv4":
		ip, err := netip.ParseAddr(val)
		return err == nil && ip.Is4()
	case "ipv6":
		ip, err := netip.ParseAddr(val)
		return err == nil && ip.Is6()
	case "uc-ip":
		_, err := netip.ParseAddr(val)
		return err == nil
	case "uc-mac":
		return regexp.MustCompile(`+"`^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$`"+`).MatchString(val)
	case "uc-timeout":
		return regexp.MustCompile(`+"`^[0-9]+[smhdw]?$`"+`).MatchString(val)
	case "uc-portrange":
		return regexp.MustCompile(`+"`^[0-9]+(-[0-9]+)?$`"+`).MatchString(val)
	case "uc-cidr4":
		parts := strings.Split(val, "/")
		if len(parts) != 2 {
			return false
		}
		prefix, err := strconv.Atoi(parts[1])
		if err != nil || prefix < 0 || prefix > 32 {
			return false
		}
		if parts[0] == "auto" {
			return true
		}
		ip, err := netip.ParseAddr(parts[0])
		return err == nil && ip.Is4()
	case "uc-cidr6":
		parts := strings.Split(val, "/")
		if len(parts) != 2 {
			return false
		}
		prefix, err := strconv.Atoi(parts[1])
		if err != nil || prefix < 0 || prefix > 128 {
			return false
		}
		if parts[0] == "auto" {
			return true
		}
		ip, err := netip.ParseAddr(parts[0])
		return err == nil && ip.Is6()
	case "hostname":
		return regexp.MustCompile("^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\\\-]{0,61}[a-zA-Z0-9])(\\\\.[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\\\-]{0,61}[a-zA-Z0-9])*$").MatchString(val)
	case "uc-cidr":
		parts := strings.Split(val, "/")
		if len(parts) != 2 {
			return false
		}
		prefix, err := strconv.Atoi(parts[1])
		if err != nil || prefix < 0 || prefix > 128 {
			return false
		}
		if parts[0] == "auto" {
			return true
		}
		_, err = netip.ParseAddr(parts[0])
		return err == nil
	case "uc-mobility":
		return regexp.MustCompile("^([0-9A-Fa-f]{4})$").MatchString(val)
	case "uc-base64":
		return regexp.MustCompile("^[a-zA-Z0-9/+]*={0,2}$").MatchString(val)
	case "uc-fqdn":
		return regexp.MustCompile("^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\\\-]{0,61}[a-zA-Z0-9])(\\\\.[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\\\-]{0,61}[a-zA-Z0-9])+$").MatchString(val)
	case "uc-host":
		if _, err := netip.ParseAddr(val); err == nil {
			return true
		}
		return regexp.MustCompile("^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\\\-]{0,61}[a-zA-Z0-9])(\\\\.[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\\\-]{0,61}[a-zA-Z0-9])*$").MatchString(val)
	case "uri":
		u, err := url.Parse(val)
		return err == nil && u.Scheme != ""
	}
	return true
}
`, schemaString)

	if err := os.WriteFile(outputFile, []byte(goCode), 0644); err != nil {
		log.Fatalf("Failed to write output file: %v", err)
	}

	fmt.Printf("Successfully generated %s\n", outputFile)
}
